### PR TITLE
version 1.1.0: nodejs child_process exec used

### PR DESCRIPTION
**Pull request by pwqw**
shelljs replaced by node child_process exec.
Added upgrade the version 4.3.\* of cordova to the dependencies.
Example added to README.md

### CODE REVIEW

**Comment by erizocosmico** [comment]
Thank you for your contribution! Merging.

**Comment by erizocosmico** [comment]
I will submit the new version to npm later today.

**Comment by pwqw** [comment]
Thanks to you...

**Comment by erizocosmico** [comment]
I've just submitted the 1.1.0 version to npm.

**Pull request merged**
